const layout = {
  "line-comment-position": "error",
  "lines-between-class-members": "error",
  "max-statements-per-line": "error",
  "padding-line-between-statements": "error",
};

const problem = {
  "array-callback-return": "error",
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-await-in-loop": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-condition": "error",
  "no-constructor-return": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-duplicate-imports": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-symbol": "error",
  "no-obj-calls": "error",
  "no-promise-executor-return": "error",
  "no-prototype-builtins": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "error",
  "no-this-before-super": "error",
  "no-undef": "error",
  "no-unmodified-loop-condition": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": "error",
  "no-use-before-define": "error",
  "no-useless-backreference": "error",
  "require-atomic-updates": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

const suggestion = {
  "accessor-pairs": "error",
  "arrow-body-style": ["error", "always"],
  "block-scoped-var": "error",
  camelcase: "error",
  "capitalized-comments": "off",
  "class-methods-use-this": "error",
  complexity: "error",
  "consistent-return": "error",
  "consistent-this": "error",
  "default-case": "error",
  "default-case-last": "error",
  "default-param-last": "error",
  "dot-notation": "error",
  eqeqeq: "error",
  "func-name-matching": "error",
  "func-names": "error",
  "func-style": "error",
  "grouped-accessor-pairs": "error",
  "guard-for-in": "error",
  "id-denylist": "error",
  "id-length": "off",
  "id-match": "error",
  "init-declarations": ["error", "never", { ignoreForLoopInit: true }],
  "max-classes-per-file": "error",
  "max-depth": "error",
  "max-lines": "off",
  "max-lines-per-function": "off",
  "max-nested-callbacks": "error",
  "max-params": "error",
  "max-statements": "off",
  "multiline-comment-style": "off",
  "new-cap": "error",
  "no-alert": "error",
  "no-array-constructor": "error",
  "no-bitwise": "error",
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-console": "warn",
  "no-continue": "error",
  "no-delete-var": "error",
  "no-div-regex": "error",
  "no-else-return": "error",
  "no-empty": "error",
  "no-empty-function": "off",
  "no-eq-null": "error",
  "no-eval": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-label": "error",
  "no-global-assign": "error",
  "no-implicit-coercion": "error",
  "no-implicit-globals": "error",
  "no-implied-eval": "error",
  "no-inline-comments": "off",
  "no-invalid-this": "error",
  "no-iterator": "error",
  "no-label-var": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-lonely-if": "error",
  "no-loop-func": "error",
  "no-magic-numbers": "off",
  "no-multi-assign": "error",
  "no-multi-str": "error",
  "no-negated-condition": "error",
  "no-nested-ternary": "error",
  "no-new": "error",
  "no-new-func": "error",
  "no-new-object": "error",
  "no-new-wrappers": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-octal": "error",
  "no-octal-escape": "error",
  "no-param-reassign": "error",
  "no-plusplus": "error",
  "no-proto": "error",
  "no-redeclare": "error",
  "no-regex-spaces": "error",
  "no-restricted-exports": "error",
  "no-restricted-globals": "error",
  "no-restricted-imports": "error",
  "no-restricted-properties": "error",
  "no-restricted-syntax": "error",
  "no-return-assign": "error",
  "no-return-await": "error",
  "no-script-url": "error",
  "no-sequences": "error",
  "no-shadow": "error",
  "no-shadow-restricted-names": "error",
  "no-ternary": "off",
  "no-throw-literal": "error",
  "no-undef-init": "error",
  "no-undefined": "error",
  "no-underscore-dangle": "error",
  "no-unneeded-ternary": "error",
  "no-unused-expressions": "error",
  "no-unused-labels": "error",
  "no-useless-call": "error",
  "no-useless-catch": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "error",
  "no-useless-constructor": "error",
  "no-useless-escape": "error",
  "no-useless-rename": "error",
  "no-useless-return": "error",
  "no-var": "error",
  "no-void": "off",
  "no-warning-comments": "error",
  "no-with": "error",
  "object-shorthand": "error",
  "one-var": ["error", "never"],
  "operator-assignment": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-destructuring": "error",
  "prefer-exponentiation-operator": "error",
  "prefer-named-capture-group": "error",
  "prefer-numeric-literals": "error",
  "prefer-object-has-own": "off",
  "prefer-object-spread": "error",
  "prefer-promise-reject-errors": "error",
  "prefer-regex-literals": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  radix: "error",
  "require-await": "error",
  "require-unicode-regexp": "error",
  "require-yield": "error",
  "sort-imports": "off",
  "sort-keys": "error",
  "sort-vars": "error",
  "spaced-comment": "error",
  strict: "error",
  "symbol-description": "error",
  "vars-on-top": "error",
  yoda: "error",
};

export default {
  overrides: [
    {
      files: ["**/{src,source,sources}/**/*.{js,jsx}"],
      parser: "@babel/eslint-parser",
    },
  ],
  parserOptions: {
    ecmaVersion: "latest",
  },
  rules: {
    ...layout,
    ...problem,
    ...suggestion,
  },
};
